# ==============================================================================
# Refer to the reference document for full details on the configuration keys:
# config/application.yaml.reference
# ==============================================================================

# REQUIRED:
# Either set in this file or set as an environment variable.
# export jwt_secret=...Your secret ...
# jwt_secret:  # [REQUIRED]

# DYNAMIC DEFAULTS:
# The following may use relative paths from the install directory
# or hard coded to be an absolute path
nodes_config_path:      config/nodes.yaml
command_directory_path: libexec
working_directory_path: libexec
job_threads: "4"

# STATIC DEFAULTS:
log_level: info

development:
  nodes_config_path:      config/nodes.example.yaml
  command_directory_path: libexec-dev
  working_directory_path: libexec-dev
  log_level:              debug
  job_threads: "4"

test:
  nodes_config_path:    config/empty.yaml
  command_directory_path: libexec-dev
  log_level:            error
  job_threads: "1"
