__meta__:
  # This section is ignored by the API

dig:
  help:
    summary: 'Run a DNS probe on the hosts'
  default:
    variables: [fqdn]
    script:
      dig $fqdn
  metal:
    script:
      dig $name

ping:
  help:
    summary: 'send ICMP ECHO_REQUEST to network hosts'
    description: >
      Check if the host is up by sending it ICMP echo requests. This utility
      wraps the standard Linux iputils library. See for further details,
      'man ping'
  default:
    variables: [IP]
    script: |-
      if [[ -z "$IP" ]]; then
        echo "The IP for node '$name' has not been set!" >&2
        exit 1
      fi
      ping -c 1 $IP
  retry:
    variables: [IP, MAX]
    script: |-
      if [[ -z "$IP" ]]; then
        echo "The IP for node '$name' has not been set!" >&2
        exit 1
      fi
      MAX=${MAX:="100"}

      count=0
      while [ $count -le $MAX ]
      do
        ((count++))
        if ping -c 1 "$IP"; then
          exit 0
        fi
      done
      exit $?

run_script:
  help:
    summary: 'Demo action for running scripts from the filesystem'
  default:
    script:
      ./default.sh $name
  metal:
    script:
      ./metal.sh $name

